-- 년, 월, 성별 별로 상품을 구매한 회원수
-- 성별 정보가 없는 경우 결과에서 제외
-- 결과는 년, 월, 성별을 기준으로 오름차순 정렬

SELECT YEAR(S.SALES_DATE) YEAR, MONTH(S.SALES_DATE) MONTH, U.GENDER, COUNT(DISTINCT S.USER_ID) USERS
FROM ONLINE_SALE S
JOIN USER_INFO U ON U.USER_ID = S.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;