-- 코드를 입력하세요
SELECT DISTINCT USER_ID, NICKNAME, CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) AS "전체주소", CONCAT(LEFT(TLNO, 3), "-", MID(TLNO, 4, 4), "-", RIGHT(TLNO, 4)) AS "전화번호" 
FROM USED_GOODS_USER AS U 
INNER JOIN (SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING COUNT(*) >= 3 ORDER BY COUNT(WRITER_ID) DESC) AS B 
ON U.USER_ID = B.WRITER_ID
ORDER BY USER_ID DESC;